### ISSUE TITLE
Can't add repository to HA

### ISSUE THREAD

**Issue by ovizii** [claudiomerli/hassio-addons#1]
I go to addons, store, manage repositories and try adding yours. I get this error:

`Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.dev/claudiomerli/hassio-addons /data/addons/git/f531c7c4 stderr: 'Cloning into '/data/addons/git/f531c7c4'... fatal: https://github.dev/claudiomerli/hassio-addons/info/refs not valid: could not determine hash algorithm; is this a git repository? '`

**Comment by claudiomerli** [comment]
Hi @ovizii, there was an incorrect link inside README. Now I've updated.

Please use: https://github.com/claudiomerli/hassio-addons

**Comment by ovizii** [comment]
I see, `.com` instead of `.dev` - thanks!
