### ISSUE TITLE
How are you using metabase?

### ISSUE THREAD

**Issue by ovizii** [claudiomerli/hassio-addons#2]
Sorry to open an issue, but you have disabled discussion on this project.

Are you using metabase to analyse HA data or external datasets?

I have set up the HA recorder to record to a [TimescaleDB ](https://github.com/expaso/hassos-addon-timescaledb)and have also started using [ltss ](https://github.com/freol35241/ltss )to save some states for long term analysis. 

I connected metabase to it but I am struggling. I watched a few meatabase tutorial videos and then thought I'd ask if you can share some tips, tricks, screenshots or anything you can share to get me started provided you also use it in a similar fashion.

**Comment by claudiomerli** [comment]
Hi @ovizii,
I’ve now enabled discussions, thanks for pointing that out.
I’m using it to manage a dashboard where I can view data about my income and expenses (household budget).

In your case, what are you struggling to do? Can you share your scenario? I’d be happy to help. Feel free to start a discussion.
